Repository volcano-sh/devices, pull requests merged in 2023-04, with the labels that each got.

#29 Fix #17 Warning UnexpectedAdmissionError
  pkg/plugin/nvidia/nvidia.go
  pkg/plugin/nvidia/utils.go
Labels: lgtm, approved

#39 Add vgpu-ci to device-plugin
  .github/workflows/main.yml
Labels: do-not-merge/contains-merge-commits, size/S

#40 Fix ci error for devices
  cmd/vgpu/main.go
  docker/amd64/Dockerfile.vgpu-ubuntu20.04
  pkg/plugin/vgpu/util/types.go
Labels: size/S
