Repository volcano-sh/devices, pull requests merged in 2024-09, with the labels that each got.

#70 Fix ci failure
  .github/workflows/main.yml
Labels: lgtm, approved, size/XS

#71 Fix ci and add OWNER info
  .golangci.yml
  OWNERS
  api/config/v1/replicas.go
  internal/cuda/api.go
  internal/rm/health.go
  internal/vgpu/pciutil.go
  internal/vgpu/vgpu.go
Labels: lgtm, size/M

#68 Enable resource naming in config
  README.md
  cmd/nvidia-device-plugin/main.go
  docs/resource-naming/README.md
Labels: lgtm, approved, size/L, ok-to-test
